on:
  workflow_dispatch: 
    

name: test.yml

jobs:
  test_openstack:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: check directory contents
        run: ls -rtlha
      - name: install openstack
        run: pip install python-openstackclient
      - run: |
            mkdir -p ~/.config/openstack
            echo "$OPENSTACK_CLOUD" > ~/.config/openstack/clouds.yaml
        env:
          OPENSTACK_CLOUD: ${{ secrets.OPENSTACK_CLOUD}}
      - run: openstack --os-cloud=$CLOUD_NAME server list 
        env:
          CLOUD_NAME: ${{secrets.CLOUD_NAME}}
          OPENSTACK_CLOUD: ${{ secrets.OPENSTACK_CLOUD}}
          
