name: Docker Build with Layer Caching

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  changes:
      name: "Changed Singularity Recipes"
      runs-on: self-hosted
      # runs-on: ubuntu-latest
      outputs:
        changed_file: ${{ steps.files.outputs.added_modified }}
      steps:
        - id: files
          uses: jitterbit/get-changed-files@b17fbb00bdc0c0f63fcf166580804b4d2cdc2a42
          with:
            format: 'json'
            files: |
              **/*
            ignore: |
              **/.github/workflows/*
    
  build:
    needs:
      - changes
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write
    strategy:
      # Keep going on other deployments if anything bloops
      fail-fast: false
      matrix:
        changed_file: ${{ fromJSON(needs.changes.outputs.changed_file) }}
    name: Check ${{matrix.changed_file}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and cache Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./${{matrix.changed_file}}
          tags: ${{ env.REGISTRY }}/github-ci:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/github-ci:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/github-ci:buildcache,mode=max
          push: true
